### ISSUE TITLE
plugins crash Ubuntu 16.04

### ISSUE THREAD

**Issue by gherardovarando** [Vaa3D/release#1]
I downloaded the latest release (v3.200) for Ubuntu, then I extracted the folder and started Vaa3D, I am able to load images and stack of images but when I try to apply a plugin Vaa3D closes without warning.

**Comment by zhizhoualan** [comment]
Please try to use "sh start_vaa3d.sh" to launch  Vaa3D.

**Comment by gherardovarando** [comment]
thanks it works with "sh start_vaa3d.sh".
